### ISSUE TITLE
进入个人博客后无法返回应用界面

### ISSUE THREAD

**Issue by wenfengtou** [Jerey-Jobs/KeepGank#1]
进入个人博客后无法返回应用界面

**Comment by Jerey-Jobs** [comment]
您好, 可以返回的 只需要从左向右滑动,  因为你可能进入的是Material Design版本的博客 那个网页点击左上角 自带一个从左往右的界面 所以会照成用户的误解 我在考虑可以把博客这个item给去掉了.

**Comment by wenfengtou** [comment]
您好，个人博客里面为什么没有头部的导航栏呢？只有博客的导航栏
![image](https://cloud.githubusercontent.com/assets/15137873/24938970/fe866438-1f6c-11e7-9790-cf3795e6ae80.png)
